name: Claude Code Review
on:
  pull_request:
    types: [opened, synchronize] # Run when PR is opened or updated
jobs:
  review:
    runs-on: ubuntu-latest
    permissions: { contents: read } # allow reading code
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Review the PR changes for potential bugs, style issues, and adherence to our standards. Provide a detailed comment with findings and suggestions.

